CREATE TABLE IF NOT EXISTS countries (
  iso2 CHAR(2) NOT NULL PRIMARY KEY,
  name_en VARCHAR(120) NOT NULL,
  name_es VARCHAR(120) NOT NULL,
  language_code VARCHAR(16) NOT NULL,
  language_name VARCHAR(80) NOT NULL,
  currency CHAR(3) NOT NULL DEFAULT 'USD',
  flag_url VARCHAR(255) NOT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_countries_lang (language_code),
  KEY idx_countries_active (active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO countries (iso2, name_en, name_es, language_code, language_name, currency, flag_url, active)
VALUES
('AD','Andorra','Andorra','ca','Catalán','EUR','https://flagsapi.com/AD/flat/64.png',1),
('AE','United Arab Emirates','Emiratos Árabes Unidos','ar','Árabe','AED','https://flagsapi.com/AE/flat/64.png',1),
('AF','Afghanistan','Afganistán','ps','Pastún','AFN','https://flagsapi.com/AF/flat/64.png',1),
('AG','Antigua and Barbuda','Antigua y Barbuda','en','English','XCD','https://flagsapi.com/AG/flat/64.png',1),
('AI','Anguilla','Anguila','en','English','XCD','https://flagsapi.com/AI/flat/64.png',1),
('AL','Albania','Albania','sq','Albanés','ALL','https://flagsapi.com/AL/flat/64.png',1),
('AM','Armenia','Armenia','hy','Armenio','AMD','https://flagsapi.com/AM/flat/64.png',1),
('AO','Angola','Angola','pt','Português','AOA','https://flagsapi.com/AO/flat/64.png',1),
('AQ','Antarctica','Antártida','en','English','USD','https://flagsapi.com/AQ/flat/64.png',1),
('AR','Argentina','Argentina','es','Español','ARS','https://flagsapi.com/AR/flat/64.png',1),
('AS','American Samoa','Samoa Americana','en','English','USD','https://flagsapi.com/AS/flat/64.png',1),
('AT','Austria','Austria','de','Deutsch','EUR','https://flagsapi.com/AT/flat/64.png',1),
('AU','Australia','Australia','en','English','AUD','https://flagsapi.com/AU/flat/64.png',1),
('AW','Aruba','Aruba','nl','Nederlands','AWG','https://flagsapi.com/AW/flat/64.png',1),
('AX','Åland Islands','Islas Åland','sv','Svenska','EUR','https://flagsapi.com/AX/flat/64.png',1),
('AZ','Azerbaijan','Azerbaiyán','az','Azerí','AZN','https://flagsapi.com/AZ/flat/64.png',1),
('BA','Bosnia and Herzegovina','Bosnia y Herzegovina','bs','Bosnio','BAM','https://flagsapi.com/BA/flat/64.png',1),
('BB','Barbados','Barbados','en','English','BBD','https://flagsapi.com/BB/flat/64.png',1),
('BD','Bangladesh','Bangladés','bn','Bengalí','BDT','https://flagsapi.com/BD/flat/64.png',1),
('BE','Belgium','Bélgica','nl','Nederlands','EUR','https://flagsapi.com/BE/flat/64.png',1),
('BF','Burkina Faso','Burkina Faso','fr','Français','XOF','https://flagsapi.com/BF/flat/64.png',1),
('BG','Bulgaria','Bulgaria','bg','Búlgaro','BGN','https://flagsapi.com/BG/flat/64.png',1),
('BH','Bahrain','Baréin','ar','Árabe','BHD','https://flagsapi.com/BH/flat/64.png',1),
('BI','Burundi','Burundi','fr','Français','BIF','https://flagsapi.com/BI/flat/64.png',1),
('BJ','Benin','Benín','fr','Français','XOF','https://flagsapi.com/BJ/flat/64.png',1),
('BL','Saint Barthélemy','San Bartolomé','fr','Français','EUR','https://flagsapi.com/BL/flat/64.png',1),
('BM','Bermuda','Bermudas','en','English','BMD','https://flagsapi.com/BM/flat/64.png',1),
('BN','Brunei','Brunéi','ms','Malayo','BND','https://flagsapi.com/BN/flat/64.png',1),
('BO','Bolivia','Bolivia','es','Español','BOB','https://flagsapi.com/BO/flat/64.png',1),
('BQ','Caribbean Netherlands','Caribe Neerlandés','nl','Nederlands','USD','https://flagsapi.com/BQ/flat/64.png',1),
('BR','Brazil','Brasil','pt','Português','BRL','https://flagsapi.com/BR/flat/64.png',1),
('BS','Bahamas','Bahamas','en','English','BSD','https://flagsapi.com/BS/flat/64.png',1),
('BT','Bhutan','Bután','dz','Dzongkha','BTN','https://flagsapi.com/BT/flat/64.png',1),
('BV','Bouvet Island','Isla Bouvet','no','Norsk','NOK','https://flagsapi.com/BV/flat/64.png',1),
('BW','Botswana','Botsuana','en','English','BWP','https://flagsapi.com/BW/flat/64.png',1),
('BY','Belarus','Bielorrusia','be','Bielorruso','BYN','https://flagsapi.com/BY/flat/64.png',1),
('BZ','Belize','Belice','en','English','BZD','https://flagsapi.com/BZ/flat/64.png',1),
('CA','Canada','Canadá','en','English','CAD','https://flagsapi.com/CA/flat/64.png',1),
('CC','Cocos Islands','Islas Cocos','en','English','AUD','https://flagsapi.com/CC/flat/64.png',1),
('CD','DR Congo','Rep. Dem. del Congo','fr','Français','CDF','https://flagsapi.com/CD/flat/64.png',1),
('CF','Central African Republic','República Centroafricana','fr','Français','XAF','https://flagsapi.com/CF/flat/64.png',1),
('CG','Congo','Congo','fr','Français','XAF','https://flagsapi.com/CG/flat/64.png',1),
('CH','Switzerland','Suiza','de','Deutsch','CHF','https://flagsapi.com/CH/flat/64.png',1),
('CI','Côte d''Ivoire','Costa de Marfil','fr','Français','XOF','https://flagsapi.com/CI/flat/64.png',1),
('CK','Cook Islands','Islas Cook','en','English','NZD','https://flagsapi.com/CK/flat/64.png',1),
('CL','Chile','Chile','es','Español','CLP','https://flagsapi.com/CL/flat/64.png',1),
('CM','Cameroon','Camerún','fr','Français','XAF','https://flagsapi.com/CM/flat/64.png',1),
('CN','China','China','zh','中文','CNY','https://flagsapi.com/CN/flat/64.png',1),
('CO','Colombia','Colombia','es','Español','COP','https://flagsapi.com/CO/flat/64.png',1),
('CR','Costa Rica','Costa Rica','es','Español','CRC','https://flagsapi.com/CR/flat/64.png',1),
('CU','Cuba','Cuba','es','Español','CUP','https://flagsapi.com/CU/flat/64.png',1),
('CV','Cabo Verde','Cabo Verde','pt','Português','CVE','https://flagsapi.com/CV/flat/64.png',1),
('CW','Curaçao','Curazao','nl','Nederlands','ANG','https://flagsapi.com/CW/flat/64.png',1),
('CX','Christmas Island','Isla de Navidad','en','English','AUD','https://flagsapi.com/CX/flat/64.png',1),
('CY','Cyprus','Chipre','el','Ελληνικά','EUR','https://flagsapi.com/CY/flat/64.png',1),
('CZ','Czechia','Chequia','cs','Čeština','CZK','https://flagsapi.com/CZ/flat/64.png',1),
('DE','Germany','Alemania','de','Deutsch','EUR','https://flagsapi.com/DE/flat/64.png',1),
('DJ','Djibouti','Yibuti','fr','Français','DJF','https://flagsapi.com/DJ/flat/64.png',1),
('DK','Denmark','Dinamarca','da','Dansk','DKK','https://flagsapi.com/DK/flat/64.png',1),
('DM','Dominica','Dominica','en','English','XCD','https://flagsapi.com/DM/flat/64.png',1),
('DO','Dominican Republic','República Dominicana','es','Español','DOP','https://flagsapi.com/DO/flat/64.png',1),
('DZ','Algeria','Argelia','ar','Árabe','DZD','https://flagsapi.com/DZ/flat/64.png',1),
('EC','Ecuador','Ecuador','es','Español','USD','https://flagsapi.com/EC/flat/64.png',1),
('EE','Estonia','Estonia','et','Eesti','EUR','https://flagsapi.com/EE/flat/64.png',1),
('EG','Egypt','Egipto','ar','Árabe','EGP','https://flagsapi.com/EG/flat/64.png',1),
('EH','Western Sahara','Sáhara Occidental','ar','Árabe','MAD','https://flagsapi.com/EH/flat/64.png',1),
('ER','Eritrea','Eritrea','ti','Tigriña','ERN','https://flagsapi.com/ER/flat/64.png',1),
('ES','Spain','España','es','Español','EUR','https://flagsapi.com/ES/flat/64.png',1),
('ET','Ethiopia','Etiopía','am','Amárico','ETB','https://flagsapi.com/ET/flat/64.png',1),
('FI','Finland','Finlandia','fi','Suomi','EUR','https://flagsapi.com/FI/flat/64.png',1),
('FJ','Fiji','Fiyi','en','English','FJD','https://flagsapi.com/FJ/flat/64.png',1),
('FK','Falkland Islands','Islas Malvinas','en','English','FKP','https://flagsapi.com/FK/flat/64.png',1),
('FM','Micronesia','Micronesia','en','English','USD','https://flagsapi.com/FM/flat/64.png',1),
('FO','Faroe Islands','Islas Feroe','fo','Feroés','DKK','https://flagsapi.com/FO/flat/64.png',1),
('FR','France','Francia','fr','Français','EUR','https://flagsapi.com/FR/flat/64.png',1),
('GA','Gabon','Gabón','fr','Français','XAF','https://flagsapi.com/GA/flat/64.png',1),
('GB','United Kingdom','Reino Unido','en','English','GBP','https://flagsapi.com/GB/flat/64.png',1),
('GD','Grenada','Granada','en','English','XCD','https://flagsapi.com/GD/flat/64.png',1),
('GE','Georgia','Georgia','ka','Georgiano','GEL','https://flagsapi.com/GE/flat/64.png',1),
('GF','French Guiana','Guayana Francesa','fr','Français','EUR','https://flagsapi.com/GF/flat/64.png',1),
('GG','Guernsey','Guernsey','en','English','GBP','https://flagsapi.com/GG/flat/64.png',1),
('GH','Ghana','Ghana','en','English','GHS','https://flagsapi.com/GH/flat/64.png',1),
('GI','Gibraltar','Gibraltar','en','English','GIP','https://flagsapi.com/GI/flat/64.png',1),
('GL','Greenland','Groenlandia','kl','Kalaallisut','DKK','https://flagsapi.com/GL/flat/64.png',1),
('GM','Gambia','Gambia','en','English','GMD','https://flagsapi.com/GM/flat/64.png',1),
('GN','Guinea','Guinea','fr','Français','GNF','https://flagsapi.com/GN/flat/64.png',1),
('GP','Guadeloupe','Guadalupe','fr','Français','EUR','https://flagsapi.com/GP/flat/64.png',1),
('GQ','Equatorial Guinea','Guinea Ecuatorial','es','Español','XAF','https://flagsapi.com/GQ/flat/64.png',1),
('GR','Greece','Grecia','el','Ελληνικά','EUR','https://flagsapi.com/GR/flat/64.png',1),
('GS','South Georgia','Georgia del Sur','en','English','GBP','https://flagsapi.com/GS/flat/64.png',1),
('GT','Guatemala','Guatemala','es','Español','GTQ','https://flagsapi.com/GT/flat/64.png',1),
('GU','Guam','Guam','en','English','USD','https://flagsapi.com/GU/flat/64.png',1),
('GW','Guinea-Bissau','Guinea-Bisáu','pt','Português','XOF','https://flagsapi.com/GW/flat/64.png',1),
('GY','Guyana','Guyana','en','English','GYD','https://flagsapi.com/GY/flat/64.png',1),
('HK','Hong Kong','Hong Kong','zh','中文','HKD','https://flagsapi.com/HK/flat/64.png',1),
('HM','Heard Island','Islas Heard y McDonald','en','English','AUD','https://flagsapi.com/HM/flat/64.png',1),
('HN','Honduras','Honduras','es','Español','HNL','https://flagsapi.com/HN/flat/64.png',1),
('HR','Croatia','Croacia','hr','Hrvatski','EUR','https://flagsapi.com/HR/flat/64.png',1),
('HT','Haiti','Haití','ht','Kreyòl','HTG','https://flagsapi.com/HT/flat/64.png',1),
('HU','Hungary','Hungría','hu','Magyar','HUF','https://flagsapi.com/HU/flat/64.png',1),
('ID','Indonesia','Indonesia','id','Bahasa Indonesia','IDR','https://flagsapi.com/ID/flat/64.png',1),
('IE','Ireland','Irlanda','en','English','EUR','https://flagsapi.com/IE/flat/64.png',1),
('IL','Israel','Israel','he','עברית','ILS','https://flagsapi.com/IL/flat/64.png',1),
('IM','Isle of Man','Isla de Man','en','English','GBP','https://flagsapi.com/IM/flat/64.png',1),
('IN','India','India','hi','हिन्दी','INR','https://flagsapi.com/IN/flat/64.png',1),
('IO','British Indian Ocean Territory','Territorio Británico del Océano Índico','en','English','USD','https://flagsapi.com/IO/flat/64.png',1),
('IQ','Iraq','Irak','ar','Árabe','IQD','https://flagsapi.com/IQ/flat/64.png',1),
('IR','Iran','Irán','fa','فارسی','IRR','https://flagsapi.com/IR/flat/64.png',1),
('IS','Iceland','Islandia','is','Íslenska','ISK','https://flagsapi.com/IS/flat/64.png',1),
('IT','Italy','Italia','it','Italiano','EUR','https://flagsapi.com/IT/flat/64.png',1),
('JE','Jersey','Jersey','en','English','GBP','https://flagsapi.com/JE/flat/64.png',1),
('JM','Jamaica','Jamaica','en','English','JMD','https://flagsapi.com/JM/flat/64.png',1),
('JO','Jordan','Jordania','ar','Árabe','JOD','https://flagsapi.com/JO/flat/64.png',1),
('JP','Japan','Japón','ja','日本語','JPY','https://flagsapi.com/JP/flat/64.png',1),
('KE','Kenya','Kenia','en','English','KES','https://flagsapi.com/KE/flat/64.png',1),
('KG','Kyrgyzstan','Kirguistán','ky','Kirguís','KGS','https://flagsapi.com/KG/flat/64.png',1),
('KH','Cambodia','Camboya','km','Jemer','KHR','https://flagsapi.com/KH/flat/64.png',1),
('KI','Kiribati','Kiribati','en','English','AUD','https://flagsapi.com/KI/flat/64.png',1),
('KM','Comoros','Comoras','ar','Árabe','KMF','https://flagsapi.com/KM/flat/64.png',1),
('KN','Saint Kitts and Nevis','San Cristóbal y Nieves','en','English','XCD','https://flagsapi.com/KN/flat/64.png',1),
('KP','North Korea','Corea del Norte','ko','한국어','KPW','https://flagsapi.com/KP/flat/64.png',1),
('KR','South Korea','Corea del Sur','ko','한국어','KRW','https://flagsapi.com/KR/flat/64.png',1),
('KW','Kuwait','Kuwait','ar','Árabe','KWD','https://flagsapi.com/KW/flat/64.png',1),
('KY','Cayman Islands','Islas Caimán','en','English','KYD','https://flagsapi.com/KY/flat/64.png',1),
('KZ','Kazakhstan','Kazajistán','kk','Kazajo','KZT','https://flagsapi.com/KZ/flat/64.png',1),
('LA','Laos','Laos','lo','Lao','LAK','https://flagsapi.com/LA/flat/64.png',1),
('LB','Lebanon','Líbano','ar','Árabe','LBP','https://flagsapi.com/LB/flat/64.png',1),
('LC','Saint Lucia','Santa Lucía','en','English','XCD','https://flagsapi.com/LC/flat/64.png',1),
('LI','Liechtenstein','Liechtenstein','de','Deutsch','CHF','https://flagsapi.com/LI/flat/64.png',1),
('LK','Sri Lanka','Sri Lanka','si','Cingalés','LKR','https://flagsapi.com/LK/flat/64.png',1),
('LR','Liberia','Liberia','en','English','LRD','https://flagsapi.com/LR/flat/64.png',1),
('LS','Lesotho','Lesoto','en','English','LSL','https://flagsapi.com/LS/flat/64.png',1),
('LT','Lithuania','Lituania','lt','Lietuvių','EUR','https://flagsapi.com/LT/flat/64.png',1),
('LU','Luxembourg','Luxemburgo','fr','Français','EUR','https://flagsapi.com/LU/flat/64.png',1),
('LV','Latvia','Letonia','lv','Latviešu','EUR','https://flagsapi.com/LV/flat/64.png',1),
('LY','Libya','Libia','ar','Árabe','LYD','https://flagsapi.com/LY/flat/64.png',1),
('MA','Morocco','Marruecos','ar','Árabe','MAD','https://flagsapi.com/MA/flat/64.png',1),
('MC','Monaco','Mónaco','fr','Français','EUR','https://flagsapi.com/MC/flat/64.png',1),
('MD','Moldova','Moldavia','ro','Română','MDL','https://flagsapi.com/MD/flat/64.png',1),
('ME','Montenegro','Montenegro','sr','Српски','EUR','https://flagsapi.com/ME/flat/64.png',1),
('MF','Saint Martin','San Martín','fr','Français','EUR','https://flagsapi.com/MF/flat/64.png',1),
('MG','Madagascar','Madagascar','fr','Français','MGA','https://flagsapi.com/MG/flat/64.png',1),
('MH','Marshall Islands','Islas Marshall','en','English','USD','https://flagsapi.com/MH/flat/64.png',1),
('MK','North Macedonia','Macedonia del Norte','mk','Macedonio','MKD','https://flagsapi.com/MK/flat/64.png',1),
('ML','Mali','Malí','fr','Français','XOF','https://flagsapi.com/ML/flat/64.png',1),
('MM','Myanmar','Myanmar','my','Birmano','MMK','https://flagsapi.com/MM/flat/64.png',1),
('MN','Mongolia','Mongolia','mn','Mongol','MNT','https://flagsapi.com/MN/flat/64.png',1),
('MO','Macao','Macao','zh','中文','MOP','https://flagsapi.com/MO/flat/64.png',1),
('MP','Northern Mariana Islands','Islas Marianas del Norte','en','English','USD','https://flagsapi.com/MP/flat/64.png',1),
('MQ','Martinique','Martinica','fr','Français','EUR','https://flagsapi.com/MQ/flat/64.png',1),
('MR','Mauritania','Mauritania','ar','Árabe','MRU','https://flagsapi.com/MR/flat/64.png',1),
('MS','Montserrat','Montserrat','en','English','XCD','https://flagsapi.com/MS/flat/64.png',1),
('MT','Malta','Malta','en','English','EUR','https://flagsapi.com/MT/flat/64.png',1),
('MU','Mauritius','Mauricio','en','English','MUR','https://flagsapi.com/MU/flat/64.png',1),
('MV','Maldives','Maldivas','dv','Divehi','MVR','https://flagsapi.com/MV/flat/64.png',1),
('MW','Malawi','Malaui','en','English','MWK','https://flagsapi.com/MW/flat/64.png',1),
('MX','Mexico','México','es','Español','MXN','https://flagsapi.com/MX/flat/64.png',1),
('MY','Malaysia','Malasia','ms','Malayo','MYR','https://flagsapi.com/MY/flat/64.png',1),
('MZ','Mozambique','Mozambique','pt','Português','MZN','https://flagsapi.com/MZ/flat/64.png',1),
('NA','Namibia','Namibia','en','English','NAD','https://flagsapi.com/NA/flat/64.png',1),
('NC','New Caledonia','Nueva Caledonia','fr','Français','XPF','https://flagsapi.com/NC/flat/64.png',1),
('NE','Niger','Níger','fr','Français','XOF','https://flagsapi.com/NE/flat/64.png',1),
('NF','Norfolk Island','Isla Norfolk','en','English','AUD','https://flagsapi.com/NF/flat/64.png',1),
('NG','Nigeria','Nigeria','en','English','NGN','https://flagsapi.com/NG/flat/64.png',1),
('NI','Nicaragua','Nicaragua','es','Español','NIO','https://flagsapi.com/NI/flat/64.png',1),
('NL','Netherlands','Países Bajos','nl','Nederlands','EUR','https://flagsapi.com/NL/flat/64.png',1),
('NO','Norway','Noruega','no','Norsk','NOK','https://flagsapi.com/NO/flat/64.png',1),
('NP','Nepal','Nepal','ne','Nepalí','NPR','https://flagsapi.com/NP/flat/64.png',1),
('NR','Nauru','Nauru','en','English','AUD','https://flagsapi.com/NR/flat/64.png',1),
('NU','Niue','Niue','en','English','NZD','https://flagsapi.com/NU/flat/64.png',1),
('NZ','New Zealand','Nueva Zelanda','en','English','NZD','https://flagsapi.com/NZ/flat/64.png',1),
('OM','Oman','Omán','ar','Árabe','OMR','https://flagsapi.com/OM/flat/64.png',1),
('PA','Panama','Panamá','es','Español','PAB','https://flagsapi.com/PA/flat/64.png',1),
('PE','Peru','Perú','es','Español','PEN','https://flagsapi.com/PE/flat/64.png',1),
('PF','French Polynesia','Polinesia Francesa','fr','Français','XPF','https://flagsapi.com/PF/flat/64.png',1),
('PG','Papua New Guinea','Papúa Nueva Guinea','en','English','PGK','https://flagsapi.com/PG/flat/64.png',1),
('PH','Philippines','Filipinas','en','English','PHP','https://flagsapi.com/PH/flat/64.png',1),
('PK','Pakistan','Pakistán','ur','Urdu','PKR','https://flagsapi.com/PK/flat/64.png',1),
('PL','Poland','Polonia','pl','Polski','PLN','https://flagsapi.com/PL/flat/64.png',1),
('PM','Saint Pierre and Miquelon','San Pedro y Miquelón','fr','Français','EUR','https://flagsapi.com/PM/flat/64.png',1),
('PN','Pitcairn','Pitcairn','en','English','NZD','https://flagsapi.com/PN/flat/64.png',1),
('PR','Puerto Rico','Puerto Rico','es','Español','USD','https://flagsapi.com/PR/flat/64.png',1),
('PS','Palestine','Palestina','ar','Árabe','ILS','https://flagsapi.com/PS/flat/64.png',1),
('PT','Portugal','Portugal','pt','Português','EUR','https://flagsapi.com/PT/flat/64.png',1),
('PW','Palau','Palaos','en','English','USD','https://flagsapi.com/PW/flat/64.png',1),
('PY','Paraguay','Paraguay','es','Español','PYG','https://flagsapi.com/PY/flat/64.png',1),
('QA','Qatar','Catar','ar','Árabe','QAR','https://flagsapi.com/QA/flat/64.png',1),
('RE','Réunion','Reunión','fr','Français','EUR','https://flagsapi.com/RE/flat/64.png',1),
('RO','Romania','Rumanía','ro','Română','RON','https://flagsapi.com/RO/flat/64.png',1),
('RS','Serbia','Serbia','sr','Српски','RSD','https://flagsapi.com/RS/flat/64.png',1),
('RU','Russia','Rusia','ru','Русский','RUB','https://flagsapi.com/RU/flat/64.png',1),
('RW','Rwanda','Ruanda','rw','Kinyarwanda','RWF','https://flagsapi.com/RW/flat/64.png',1),
('SA','Saudi Arabia','Arabia Saudita','ar','Árabe','SAR','https://flagsapi.com/SA/flat/64.png',1),
('SB','Solomon Islands','Islas Salomón','en','English','SBD','https://flagsapi.com/SB/flat/64.png',1),
('SC','Seychelles','Seychelles','en','English','SCR','https://flagsapi.com/SC/flat/64.png',1),
('SD','Sudan','Sudán','ar','Árabe','SDG','https://flagsapi.com/SD/flat/64.png',1),
('SE','Sweden','Suecia','sv','Svenska','SEK','https://flagsapi.com/SE/flat/64.png',1),
('SG','Singapore','Singapur','en','English','SGD','https://flagsapi.com/SG/flat/64.png',1),
('SH','Saint Helena','Santa Elena','en','English','SHP','https://flagsapi.com/SH/flat/64.png',1),
('SI','Slovenia','Eslovenia','sl','Slovenščina','EUR','https://flagsapi.com/SI/flat/64.png',1),
('SJ','Svalbard and Jan Mayen','Svalbard y Jan Mayen','no','Norsk','NOK','https://flagsapi.com/SJ/flat/64.png',1),
('SK','Slovakia','Eslovaquia','sk','Slovenčina','EUR','https://flagsapi.com/SK/flat/64.png',1),
('SL','Sierra Leone','Sierra Leona','en','English','SLE','https://flagsapi.com/SL/flat/64.png',1),
('SM','San Marino','San Marino','it','Italiano','EUR','https://flagsapi.com/SM/flat/64.png',1),
('SN','Senegal','Senegal','fr','Français','XOF','https://flagsapi.com/SN/flat/64.png',1),
('SO','Somalia','Somalia','so','Somalí','SOS','https://flagsapi.com/SO/flat/64.png',1),
('SR','Suriname','Surinam','nl','Nederlands','SRD','https://flagsapi.com/SR/flat/64.png',1),
('SS','South Sudan','Sudán del Sur','en','English','SSP','https://flagsapi.com/SS/flat/64.png',1),
('ST','São Tomé and Príncipe','Santo Tomé y Príncipe','pt','Português','STN','https://flagsapi.com/ST/flat/64.png',1),
('SV','El Salvador','El Salvador','es','Español','USD','https://flagsapi.com/SV/flat/64.png',1),
('SX','Sint Maarten','Sint Maarten','nl','Nederlands','ANG','https://flagsapi.com/SX/flat/64.png',1),
('SY','Syria','Siria','ar','Árabe','SYP','https://flagsapi.com/SY/flat/64.png',1),
('SZ','Eswatini','Esuatini','en','English','SZL','https://flagsapi.com/SZ/flat/64.png',1),
('TC','Turks and Caicos Islands','Islas Turcas y Caicos','en','English','USD','https://flagsapi.com/TC/flat/64.png',1),
('TD','Chad','Chad','fr','Français','XAF','https://flagsapi.com/TD/flat/64.png',1),
('TF','French Southern Territories','Territorios Australes Franceses','fr','Français','EUR','https://flagsapi.com/TF/flat/64.png',1),
('TG','Togo','Togo','fr','Français','XOF','https://flagsapi.com/TG/flat/64.png',1),
('TH','Thailand','Tailandia','th','ไทย','THB','https://flagsapi.com/TH/flat/64.png',1),
('TJ','Tajikistan','Tayikistán','tg','Tayiko','TJS','https://flagsapi.com/TJ/flat/64.png',1),
('TK','Tokelau','Tokelau','en','English','NZD','https://flagsapi.com/TK/flat/64.png',1),
('TL','Timor-Leste','Timor Oriental','pt','Português','USD','https://flagsapi.com/TL/flat/64.png',1),
('TM','Turkmenistan','Turkmenistán','tk','Turcomano','TMT','https://flagsapi.com/TM/flat/64.png',1),
('TN','Tunisia','Túnez','ar','Árabe','TND','https://flagsapi.com/TN/flat/64.png',1),
('TO','Tonga','Tonga','en','English','TOP','https://flagsapi.com/TO/flat/64.png',1),
('TR','Turkey','Turquía','tr','Türkçe','TRY','https://flagsapi.com/TR/flat/64.png',1),
('TT','Trinidad and Tobago','Trinidad y Tobago','en','English','TTD','https://flagsapi.com/TT/flat/64.png',1),
('TV','Tuvalu','Tuvalu','en','English','AUD','https://flagsapi.com/TV/flat/64.png',1),
('TW','Taiwan','Taiwán','zh','中文','TWD','https://flagsapi.com/TW/flat/64.png',1),
('TZ','Tanzania','Tanzania','sw','Swahili','TZS','https://flagsapi.com/TZ/flat/64.png',1),
('UA','Ukraine','Ucrania','uk','Українська','UAH','https://flagsapi.com/UA/flat/64.png',1),
('UG','Uganda','Uganda','en','English','UGX','https://flagsapi.com/UG/flat/64.png',1),
('UM','U.S. Outlying Islands','Islas Ultramarinas de EE.UU.','en','English','USD','https://flagsapi.com/UM/flat/64.png',1),
('US','United States','Estados Unidos','en','English','USD','https://flagsapi.com/US/flat/64.png',1),
('UY','Uruguay','Uruguay','es','Español','UYU','https://flagsapi.com/UY/flat/64.png',1),
('UZ','Uzbekistan','Uzbekistán','uz','Uzbeko','UZS','https://flagsapi.com/UZ/flat/64.png',1),
('VA','Vatican City','Ciudad del Vaticano','it','Italiano','EUR','https://flagsapi.com/VA/flat/64.png',1),
('VC','Saint Vincent and the Grenadines','San Vicente y las Granadinas','en','English','XCD','https://flagsapi.com/VC/flat/64.png',1),
('VE','Venezuela','Venezuela','es','Español','VES','https://flagsapi.com/VE/flat/64.png',1),
('VG','British Virgin Islands','Islas Vírgenes Británicas','en','English','USD','https://flagsapi.com/VG/flat/64.png',1),
('VI','U.S. Virgin Islands','Islas Vírgenes de EE.UU.','en','English','USD','https://flagsapi.com/VI/flat/64.png',1),
('VN','Vietnam','Vietnam','vi','Tiếng Việt','VND','https://flagsapi.com/VN/flat/64.png',1),
('VU','Vanuatu','Vanuatu','bi','Bislama','VUV','https://flagsapi.com/VU/flat/64.png',1),
('WF','Wallis and Futuna','Wallis y Futuna','fr','Français','XPF','https://flagsapi.com/WF/flat/64.png',1),
('WS','Samoa','Samoa','sm','Samoano','WST','https://flagsapi.com/WS/flat/64.png',1),
('XK','Kosovo','Kosovo','sq','Albanés','EUR','https://flagsapi.com/XK/flat/64.png',1),
('YE','Yemen','Yemen','ar','Árabe','YER','https://flagsapi.com/YE/flat/64.png',1),
('YT','Mayotte','Mayotte','fr','Français','EUR','https://flagsapi.com/YT/flat/64.png',1),
('ZA','South Africa','Sudáfrica','en','English','ZAR','https://flagsapi.com/ZA/flat/64.png',1),
('ZM','Zambia','Zambia','en','English','ZMW','https://flagsapi.com/ZM/flat/64.png',1),
('ZW','Zimbabwe','Zimbabue','en','English','ZWL','https://flagsapi.com/ZW/flat/64.png',1)
ON DUPLICATE KEY UPDATE
  name_en=VALUES(name_en),
  name_es=VALUES(name_es),
  language_code=VALUES(language_code),
  language_name=VALUES(language_name),
  currency=VALUES(currency),
  flag_url=VALUES(flag_url),
  active=VALUES(active);
