-- =============================================================================
-- V30 — DoorDrop notification event catalog
-- Real event-to-template routing for auth, shipments, billing, marketplace and support.
-- =============================================================================

ALTER TABLE email_templates
  MODIFY category ENUM('auth','shipments','billing','omnichannel','marketplace') NOT NULL DEFAULT 'auth';

ALTER TABLE email_logs
  ADD COLUMN entity_type VARCHAR(50) NULL AFTER shipment_id,
  ADD COLUMN entity_id VARCHAR(191) NULL AFTER entity_type,
  ADD COLUMN audience VARCHAR(40) NULL AFTER entity_id,
  ADD COLUMN template_id VARCHAR(80) NULL AFTER audience,
  ADD INDEX idx_email_logs_entity (entity_type, entity_id, event_code, audience, status),
  ADD UNIQUE KEY uq_email_entity_event_audience (entity_type, entity_id, event_code, audience, to_email);

CREATE TABLE IF NOT EXISTS email_notification_events (
  event_code VARCHAR(100) PRIMARY KEY,
  template_id VARCHAR(80) NOT NULL,
  category ENUM('auth','shipments','billing','omnichannel','marketplace') NOT NULL,
  label VARCHAR(150) NOT NULL,
  description VARCHAR(500) NULL,
  audience VARCHAR(40) NOT NULL DEFAULT 'customer',
  is_enabled TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_email_event_template FOREIGN KEY (template_id) REFERENCES email_templates(id) ON DELETE RESTRICT,
  INDEX idx_email_events_category (category, is_enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO email_templates (id, category, name, description, variables_json) VALUES
('shipment_received', 'shipments', 'Envío recibido', 'Confirma que DoorDrop recibió el envío y explica si la etiqueta sigue en preparación.', JSON_ARRAY('userName','trackingCode','statusLabel','trackingUrl','supportUrl')),
('shipment_status', 'shipments', 'Actualización de envío', 'Estado logístico público con seguimiento real.', JSON_ARRAY('userName','trackingCode','statusTitle','statusLabel','trackingUrl','carrierName','destinationCity','supportUrl')),
('shipment_issue', 'shipments', 'Incidencia de envío', 'Avisa de una incidencia o validación pendiente sin exponer detalles internos.', JSON_ARRAY('userName','trackingCode','issueTitle','issueDescription','ticketUrl','supportUrl')),
('shipment_cancellation_customer', 'shipments', 'Cancelación y reembolso', 'Comunicación al cliente sobre una solicitud, aprobación o rechazo de cancelación.', JSON_ARRAY('userName','trackingCode','statusTitle','statusLabel','amount','currency','ticketUrl','walletUrl')),
('shipment_cancellation_internal', 'shipments', 'Revisión interna de cancelación', 'Aviso operativo para revisar una solicitud de cancelación.', JSON_ARRAY('customerName','customerEmail','trackingCode','reason','amount','currency','ticketUrl')),
('wallet_topup_failed', 'billing', 'Recarga no completada', 'Avisa que una recarga no pudo acreditarse.', JSON_ARRAY('userName','amount','currency','paymentMethod','billingUrl','errorMessage')),
('marketplace_order_buyer', 'marketplace', 'Compra confirmada', 'Confirmación de compra para el comprador.', JSON_ARRAY('userName','orderNumber','listingTitle','totalAmount','currency','orderStatus','orderUrl','sellerName')),
('marketplace_order_seller', 'marketplace', 'Nueva venta', 'Aviso de nueva venta para el vendedor.', JSON_ARRAY('sellerName','orderNumber','listingTitle','totalAmount','currency','buyerName','orderUrl','shippingAddressUrl')),
('marketplace_order_status', 'marketplace', 'Estado de pedido', 'Actualización del pedido y seguimiento cuando existe una guía real.', JSON_ARRAY('userName','orderNumber','listingTitle','orderStatus','trackingCode','trackingUrl','orderUrl')),
('marketplace_offer', 'marketplace', 'Actualización de oferta', 'Aviso de oferta recibida o respondida.', JSON_ARRAY('userName','listingTitle','offerAmount','currency','offerStatus','offerUrl','buyerName')),
('ai_handoff_customer', 'omnichannel', 'Asistencia humana solicitada', 'Confirma al cliente que un agente continuará la conversación.', JSON_ARRAY('userName','ticketId','ticketUrl','summary','statusLabel')),
('ai_handoff_internal', 'omnichannel', 'Nueva escalación AI', 'Aviso interno de una conversación que requiere atención humana.', JSON_ARRAY('customerName','customerEmail','ticketId','ticketUrl','channel','reason','summary')),
('ticket_reply_customer', 'omnichannel', 'Respuesta de soporte', 'Avisa al cliente que un agente respondió su ticket.', JSON_ARRAY('userName','ticketId','ticketUrl','agentName','replyPreview')),
('ticket_resolved_customer', 'omnichannel', 'Ticket resuelto', 'Confirma la resolución de un ticket.', JSON_ARRAY('userName','ticketId','ticketUrl','resolvedAt'))
ON DUPLICATE KEY UPDATE
  category = VALUES(category), name = VALUES(name), description = VALUES(description), variables_json = VALUES(variables_json);

INSERT INTO email_template_translations (id, template_id, language, subject, preheader, body_html, body_text, is_active) VALUES
('trans_ship_received_es', 'shipment_received', 'es', 'Recibimos tu envío {{trackingCode}}', 'Tu envío está siendo preparado en DoorDrop.', '<!doctype html><html><body style="font-family:Arial,sans-serif;background:#f8fafc;padding:28px;color:#0f172a"><div style="max-width:560px;margin:auto;background:#fff;border:1px solid #e2e8f0;border-radius:16px;padding:30px"><h1>Recibimos tu envío</h1><p>Hola <strong>{{userName}}</strong>, hemos recibido tu envío <strong>{{trackingCode}}</strong>.</p><p>Estado actual: <strong>{{statusLabel}}</strong>. Si la etiqueta todavía está en preparación, se actualizará cuando la red logística la confirme.</p><p><a href="{{trackingUrl}}">Ver seguimiento</a> · <a href="{{supportUrl}}">Soporte</a></p></div></body></html>', 'Hola {{userName}}, recibimos tu envío {{trackingCode}}. Estado: {{statusLabel}}. Seguimiento: {{trackingUrl}}', 1),
('trans_ship_status_es', 'shipment_status', 'es', '{{statusTitle}} · {{trackingCode}}', 'Actualización de tu envío en DoorDrop.', '<!doctype html><html><body style="font-family:Arial,sans-serif;background:#f8fafc;padding:28px;color:#0f172a"><div style="max-width:560px;margin:auto;background:#fff;border:1px solid #e2e8f0;border-radius:16px;padding:30px"><h1>{{statusTitle}}</h1><p>Hola <strong>{{userName}}</strong>, tu envío <strong>{{trackingCode}}</strong> tiene una nueva actualización.</p><p><strong>{{statusLabel}}</strong><br>Transportista: {{carrierName}}<br>Destino: {{destinationCity}}</p><p><a href="{{trackingUrl}}">Ver seguimiento</a> · <a href="{{supportUrl}}">Soporte</a></p></div></body></html>', 'Hola {{userName}}, tu envío {{trackingCode}} está en estado {{statusLabel}}. Seguimiento: {{trackingUrl}}', 1),
('trans_ship_issue_es', 'shipment_issue', 'es', 'Necesitamos revisar tu envío {{trackingCode}}', 'Hay una incidencia que requiere atención.', '<!doctype html><html><body style="font-family:Arial,sans-serif;background:#f8fafc;padding:28px;color:#0f172a"><div style="max-width:560px;margin:auto;background:#fff;border:1px solid #fed7aa;border-radius:16px;padding:30px"><h1>{{issueTitle}}</h1><p>Hola <strong>{{userName}}</strong>, el envío <strong>{{trackingCode}}</strong> necesita atención.</p><p>{{issueDescription}}</p><p><a href="{{ticketUrl}}">Abrir ticket</a> · <a href="{{supportUrl}}">Soporte</a></p></div></body></html>', 'Hola {{userName}}, el envío {{trackingCode}} necesita atención: {{issueDescription}}. Ticket: {{ticketUrl}}', 1),
('trans_cancel_customer_es', 'shipment_cancellation_customer', 'es', '{{statusTitle}} · {{trackingCode}}', 'Actualización de tu solicitud de cancelación.', '<!doctype html><html><body style="font-family:Arial,sans-serif;background:#f8fafc;padding:28px;color:#0f172a"><div style="max-width:560px;margin:auto;background:#fff;border:1px solid #e2e8f0;border-radius:16px;padding:30px"><h1>{{statusTitle}}</h1><p>Hola <strong>{{userName}}</strong>, tu solicitud relacionada con <strong>{{trackingCode}}</strong> fue actualizada.</p><p>Estado: <strong>{{statusLabel}}</strong><br>Importe: {{amount}} {{currency}}</p><p><a href="{{ticketUrl}}">Ver ticket</a> · <a href="{{walletUrl}}">Ver monedero</a></p></div></body></html>', 'Hola {{userName}}, tu solicitud {{trackingCode}} fue actualizada: {{statusLabel}}. Importe: {{amount}} {{currency}}.', 1),
('trans_cancel_internal_es', 'shipment_cancellation_internal', 'es', 'Nueva solicitud de cancelación · {{trackingCode}}', 'Hay una solicitud pendiente de revisión.', '<!doctype html><html><body style="font-family:Arial,sans-serif;background:#f8fafc;padding:28px;color:#0f172a"><div style="max-width:560px;margin:auto;background:#fff;border:1px solid #fed7aa;border-radius:16px;padding:30px"><h1>Nueva solicitud de cancelación</h1><p>Cliente: <strong>{{customerName}}</strong> ({{customerEmail}})</p><p>Envío: <strong>{{trackingCode}}</strong><br>Importe: {{amount}} {{currency}}<br>Motivo: {{reason}}</p><p><a href="{{ticketUrl}}">Revisar ticket</a></p></div></body></html>', 'Nueva solicitud de cancelación para {{trackingCode}}. Cliente: {{customerName}}. Motivo: {{reason}}. Ticket: {{ticketUrl}}', 1),
('trans_wallet_failed_es', 'wallet_topup_failed', 'es', 'No se completó tu recarga DoorDrop', 'La recarga no pudo acreditarse.', '<!doctype html><html><body style="font-family:Arial,sans-serif;background:#f8fafc;padding:28px;color:#0f172a"><div style="max-width:560px;margin:auto;background:#fff;border:1px solid #fecaca;border-radius:16px;padding:30px"><h1>Recarga no completada</h1><p>Hola <strong>{{userName}}</strong>, no pudimos completar la recarga de <strong>{{amount}} {{currency}}</strong>.</p><p>Método: {{paymentMethod}}<br>{{errorMessage}}</p><p><a href="{{billingUrl}}">Revisar mi monedero</a></p></div></body></html>', 'Hola {{userName}}, no se completó tu recarga de {{amount}} {{currency}}. Revisa tu monedero: {{billingUrl}}', 1),
('trans_market_buyer_es', 'marketplace_order_buyer', 'es', 'Compra confirmada · {{orderNumber}}', 'Tu compra de {{listingTitle}} fue confirmada.', '<!doctype html><html><body style="font-family:Arial,sans-serif;background:#f8fafc;padding:28px;color:#0f172a"><div style="max-width:560px;margin:auto;background:#fff;border:1px solid #e2e8f0;border-radius:16px;padding:30px"><h1>Compra confirmada</h1><p>Hola <strong>{{userName}}</strong>, recibimos tu compra <strong>{{orderNumber}}</strong>.</p><p>Producto: {{listingTitle}}<br>Total: <strong>{{totalAmount}} {{currency}}</strong><br>Estado: {{orderStatus}}<br>Vendedor: {{sellerName}}</p><p><a href="{{orderUrl}}">Ver pedido</a></p></div></body></html>', 'Hola {{userName}}, compra {{orderNumber}} confirmada. Producto: {{listingTitle}}. Total: {{totalAmount}} {{currency}}. Pedido: {{orderUrl}}', 1),
('trans_market_seller_es', 'marketplace_order_seller', 'es', 'Nueva venta · {{orderNumber}}', 'Tienes una nueva venta en DoorDrop.', '<!doctype html><html><body style="font-family:Arial,sans-serif;background:#f8fafc;padding:28px;color:#0f172a"><div style="max-width:560px;margin:auto;background:#fff;border:1px solid #e2e8f0;border-radius:16px;padding:30px"><h1>Nueva venta</h1><p>Hola <strong>{{sellerName}}</strong>, recibiste el pedido <strong>{{orderNumber}}</strong>.</p><p>Producto: {{listingTitle}}<br>Total: <strong>{{totalAmount}} {{currency}}</strong><br>Comprador: {{buyerName}}</p><p>Consulta la dirección de envío únicamente desde el panel protegido.</p><p><a href="{{orderUrl}}">Preparar pedido</a></p></div></body></html>', 'Hola {{sellerName}}, recibiste la venta {{orderNumber}} de {{listingTitle}} por {{totalAmount}} {{currency}}. Pedido: {{orderUrl}}', 1),
('trans_market_status_es', 'marketplace_order_status', 'es', 'Actualización del pedido {{orderNumber}}', 'Tu pedido tiene una nueva actualización.', '<!doctype html><html><body style="font-family:Arial,sans-serif;background:#f8fafc;padding:28px;color:#0f172a"><div style="max-width:560px;margin:auto;background:#fff;border:1px solid #e2e8f0;border-radius:16px;padding:30px"><h1>Actualización del pedido</h1><p>Hola <strong>{{userName}}</strong>, el pedido <strong>{{orderNumber}}</strong> está ahora en estado <strong>{{orderStatus}}</strong>.</p><p>Producto: {{listingTitle}}<br>Seguimiento: {{trackingCode}}</p><p><a href="{{orderUrl}}">Ver pedido</a> · <a href="{{trackingUrl}}">Ver seguimiento</a></p></div></body></html>', 'Hola {{userName}}, el pedido {{orderNumber}} está en estado {{orderStatus}}. Pedido: {{orderUrl}}', 1),
('trans_market_offer_es', 'marketplace_offer', 'es', 'Actualización de tu oferta · {{listingTitle}}', 'Hay una actualización en una oferta del Marketplace.', '<!doctype html><html><body style="font-family:Arial,sans-serif;background:#f8fafc;padding:28px;color:#0f172a"><div style="max-width:560px;margin:auto;background:#fff;border:1px solid #e2e8f0;border-radius:16px;padding:30px"><h1>Actualización de oferta</h1><p>Hola <strong>{{userName}}</strong>, la oferta para <strong>{{listingTitle}}</strong> está en estado <strong>{{offerStatus}}</strong>.</p><p>Importe: {{offerAmount}} {{currency}}<br>Participante: {{buyerName}}</p><p><a href="{{offerUrl}}">Ver oferta</a></p></div></body></html>', 'Hola {{userName}}, tu oferta para {{listingTitle}} está {{offerStatus}}. Ver oferta: {{offerUrl}}', 1),
('trans_ai_customer_es', 'ai_handoff_customer', 'es', 'Un agente continuará tu asistencia', 'Hemos creado una atención para continuar contigo.', '<!doctype html><html><body style="font-family:Arial,sans-serif;background:#f8fafc;padding:28px;color:#0f172a"><div style="max-width:560px;margin:auto;background:#fff;border:1px solid #bfdbfe;border-radius:16px;padding:30px"><h1>Un agente continuará tu asistencia</h1><p>Hola <strong>{{userName}}</strong>, hemos transferido tu solicitud a un agente DoorDrop.</p><p>Estado: {{statusLabel}}<br>{{summary}}</p><p><a href="{{ticketUrl}}">Ver ticket</a></p></div></body></html>', 'Hola {{userName}}, un agente continuará tu asistencia. Ticket: {{ticketUrl}}', 1),
('trans_ai_internal_es', 'ai_handoff_internal', 'es', 'Nueva escalación AI · ticket {{ticketId}}', 'Una conversación necesita atención humana.', '<!doctype html><html><body style="font-family:Arial,sans-serif;background:#f8fafc;padding:28px;color:#0f172a"><div style="max-width:560px;margin:auto;background:#fff;border:1px solid #fed7aa;border-radius:16px;padding:30px"><h1>Nueva escalación AI</h1><p>Cliente: <strong>{{customerName}}</strong> ({{customerEmail}})<br>Canal: {{channel}}<br>Motivo: {{reason}}</p><p>{{summary}}</p><p><a href="{{ticketUrl}}">Abrir ticket</a></p></div></body></html>', 'Nueva escalación AI del cliente {{customerName}}. Ticket: {{ticketUrl}}. Motivo: {{reason}}', 1),
('trans_ticket_reply_es', 'ticket_reply_customer', 'es', 'Tu ticket tiene una nueva respuesta', 'Un agente DoorDrop respondió tu solicitud.', '<!doctype html><html><body style="font-family:Arial,sans-serif;background:#f8fafc;padding:28px;color:#0f172a"><div style="max-width:560px;margin:auto;background:#fff;border:1px solid #e2e8f0;border-radius:16px;padding:30px"><h1>Tu ticket tiene una nueva respuesta</h1><p>Hola <strong>{{userName}}</strong>, {{agentName}} respondió tu solicitud.</p><p>{{replyPreview}}</p><p><a href="{{ticketUrl}}">Ver ticket</a></p></div></body></html>', 'Hola {{userName}}, {{agentName}} respondió tu ticket. Ver respuesta: {{ticketUrl}}', 1),
('trans_ticket_resolved_es', 'ticket_resolved_customer', 'es', 'Ticket resuelto · {{ticketId}}', 'Tu solicitud fue marcada como resuelta.', '<!doctype html><html><body style="font-family:Arial,sans-serif;background:#f8fafc;padding:28px;color:#0f172a"><div style="max-width:560px;margin:auto;background:#fff;border:1px solid #bbf7d0;border-radius:16px;padding:30px"><h1>Ticket resuelto</h1><p>Hola <strong>{{userName}}</strong>, tu solicitud <strong>{{ticketId}}</strong> fue marcada como resuelta.</p><p>Si todavía necesitas ayuda, puedes responder desde el panel.</p><p><a href="{{ticketUrl}}">Ver ticket</a></p></div></body></html>', 'Hola {{userName}}, tu ticket {{ticketId}} fue resuelto. Ver ticket: {{ticketUrl}}', 1)
ON DUPLICATE KEY UPDATE subject=VALUES(subject), preheader=VALUES(preheader), body_html=VALUES(body_html), body_text=VALUES(body_text), is_active=VALUES(is_active);

INSERT INTO email_notification_events (event_code, template_id, category, label, description, audience, is_enabled) VALUES
('user_registered','auth_welcome','auth','Registro de cuenta','Bienvenida tras crear una cuenta','customer',1),
('shipment_received','shipment_received','shipments','Envío recibido','Confirmación de recepción del envío','customer',1),
('shipment_status_updated','shipment_status','shipments','Estado actualizado','Actualización logística no clasificada','customer',1),
('shipment_pending_provider','shipment_status','shipments','Etiqueta en preparación','El proveedor todavía está preparando la etiqueta','customer',1),
('shipment_pending_label','shipment_status','shipments','Etiqueta pendiente','La etiqueta aún no está disponible','customer',1),
('shipment_label_ready','shipment_status','shipments','Etiqueta lista','La etiqueta está disponible','customer',1),
('shipment_tramitado','shipment_status','shipments','Envío tramitado','El envío fue procesado','customer',1),
('shipment_en_transito','shipment_status','shipments','En tránsito','El envío está en tránsito','customer',1),
('shipment_en_reparto','shipment_status','shipments','En reparto','El envío está en reparto','customer',1),
('shipment_entregado','shipment_status','shipments','Entregado','El envío fue entregado','customer',1),
('shipment_incidencia','shipment_issue','shipments','Incidencia','El envío requiere atención','customer',1),
('shipment_devuelto','shipment_status','shipments','Devuelto','El envío fue devuelto','customer',1),
('shipment_cancelado','shipment_status','shipments','Cancelado','El envío fue cancelado','customer',1),
('cancellation_request_received','shipment_cancellation_customer','shipments','Cancelación recibida','Solicitud de cancelación recibida','customer',1),
('cancellation_request_internal','shipment_cancellation_internal','shipments','Revisión de cancelación','Aviso interno de cancelación','internal',1),
('cancellation_approved_refunded','shipment_cancellation_customer','shipments','Reembolso aprobado','Reembolso acreditado','customer',1),
('cancellation_rejected','shipment_cancellation_customer','shipments','Cancelación revisada','Solicitud revisada','customer',1),
('wallet_topup_success','wallet_topup_success','billing','Recarga exitosa','Saldo acreditado','customer',1),
('wallet_topup_failed','wallet_topup_failed','billing','Recarga fallida','Recarga no acreditada','customer',1),
('marketplace_order_paid_buyer','marketplace_order_buyer','marketplace','Compra confirmada','Confirmación al comprador','buyer',1),
('marketplace_sale_received','marketplace_order_seller','marketplace','Nueva venta','Aviso al vendedor','seller',1),
('marketplace_order_status_buyer','marketplace_order_status','marketplace','Estado del pedido al comprador','Actualización del pedido','buyer',1),
('marketplace_order_status_seller','marketplace_order_status','marketplace','Estado del pedido al vendedor','Actualización operativa','seller',1),
('marketplace_offer_received','marketplace_offer','marketplace','Oferta recibida','Nueva oferta','seller',1),
('marketplace_offer_updated','marketplace_offer','marketplace','Oferta actualizada','Oferta respondida','buyer',1),
('ai_handoff_customer','ai_handoff_customer','omnichannel','AI a humano — cliente','Confirmación al cliente','customer',1),
('ai_handoff_internal','ai_handoff_internal','omnichannel','AI a humano — equipo','Aviso al equipo','internal',1),
('omnichannel_handoff_customer','ai_handoff_customer','omnichannel','Transferencia — cliente','Confirmación de transferencia','customer',1),
('omnichannel_handoff_internal','ai_handoff_internal','omnichannel','Transferencia — equipo','Aviso de transferencia','internal',1),
('ticket_reply_customer','ticket_reply_customer','omnichannel','Respuesta de agente','Nueva respuesta en ticket','customer',1),
('ticket_resolved_customer','ticket_resolved_customer','omnichannel','Ticket resuelto','Cierre de ticket','customer',1)
ON DUPLICATE KEY UPDATE
  template_id=VALUES(template_id), category=VALUES(category), label=VALUES(label), description=VALUES(description), audience=VALUES(audience);
