-- DoorDrop V36: email verification for password registrations.
-- Tokens are stored only as SHA-256 hashes and expire after four hours.

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS language CHAR(2) NOT NULL DEFAULT 'es',
  ADD COLUMN IF NOT EXISTS email_verified_at DATETIME NULL,
  ADD COLUMN IF NOT EXISTS email_verification_required TINYINT(1) NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS email_verification_tokens (
  id CHAR(36) PRIMARY KEY,
  user_id CHAR(36) NOT NULL,
  token_hash CHAR(64) NOT NULL,
  expires_at DATETIME NOT NULL,
  used_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  request_ip VARCHAR(45) NULL,
  UNIQUE KEY uq_evt_token_hash (token_hash),
  INDEX idx_evt_user_id (user_id),
  INDEX idx_evt_expires_used (expires_at, used_at),
  CONSTRAINT fk_evt_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO email_templates (id, category, name, description, variables_json) VALUES
('email_verification', 'auth', 'Verificación de correo', 'Confirma el correo de una cuenta creada con email y contraseña.', JSON_ARRAY('userName','userEmail','verificationUrl','expirationHours','loginUrl'))
ON DUPLICATE KEY UPDATE
  category = VALUES(category), name = VALUES(name), description = VALUES(description), variables_json = VALUES(variables_json);

INSERT INTO email_template_translations (id, template_id, language, subject, preheader, body_html, body_text, is_active) VALUES
('trans_email_verify_es', 'email_verification', 'es', 'Confirma tu correo de DoorDrop', 'Activa tu cuenta con un clic. El enlace es válido durante 4 horas.', '<!doctype html><html lang="es"><body style="margin:0;background:#f8fafc;font-family:Arial,sans-serif;color:#0f172a;padding:28px 14px"><div style="max-width:560px;margin:auto;background:#fff;border:1px solid #e2e8f0;border-radius:18px;padding:32px"><div style="font-size:24px;font-weight:800;margin-bottom:24px">Door<span style="color:#2563eb">Drop</span></div><h1 style="font-size:24px;margin:0 0 14px">Confirma tu correo</h1><p style="font-size:14px;line-height:1.6;color:#475569">Hola <strong>{{userName}}</strong>. Confirma <strong>{{userEmail}}</strong> para proteger tu cuenta y acceder a DoorDrop.</p><p style="text-align:center;margin:28px 0"><a href="{{verificationUrl}}" style="display:inline-block;background:#2563eb;color:#fff;padding:14px 24px;border-radius:10px;text-decoration:none;font-weight:700">Verificar mi correo</a></p><p style="font-size:13px;line-height:1.6;color:#64748b">Este enlace es válido durante <strong>{{expirationHours}} horas</strong> y solo puede utilizarse una vez. Si no creaste esta cuenta, puedes ignorar este mensaje.</p><p style="font-size:12px;color:#94a3b8;margin-top:28px">DoorDrop · Enlace de seguridad para tu cuenta</p></div></body></html>', 'Hola {{userName}}, confirma tu correo {{userEmail}} en este enlace: {{verificationUrl}}. El enlace es válido durante {{expirationHours}} horas y solo puede usarse una vez.', 1),
('trans_email_verify_en', 'email_verification', 'en', 'Confirm your DoorDrop email', 'Activate your account with one click. The link is valid for 4 hours.', '<!doctype html><html lang="en"><body style="margin:0;background:#f8fafc;font-family:Arial,sans-serif;color:#0f172a;padding:28px 14px"><div style="max-width:560px;margin:auto;background:#fff;border:1px solid #e2e8f0;border-radius:18px;padding:32px"><div style="font-size:24px;font-weight:800;margin-bottom:24px">Door<span style="color:#2563eb">Drop</span></div><h1 style="font-size:24px;margin:0 0 14px">Confirm your email</h1><p style="font-size:14px;line-height:1.6;color:#475569">Hello <strong>{{userName}}</strong>. Confirm <strong>{{userEmail}}</strong> to protect your account and access DoorDrop.</p><p style="text-align:center;margin:28px 0"><a href="{{verificationUrl}}" style="display:inline-block;background:#2563eb;color:#fff;padding:14px 24px;border-radius:10px;text-decoration:none;font-weight:700">Verify my email</a></p><p style="font-size:13px;line-height:1.6;color:#64748b">This link is valid for <strong>{{expirationHours}} hours</strong> and can only be used once. If you did not create this account, you can ignore this message.</p><p style="font-size:12px;color:#94a3b8;margin-top:28px">DoorDrop · Account security link</p></div></body></html>', 'Hello {{userName}}, confirm your email {{userEmail}} here: {{verificationUrl}}. The link is valid for {{expirationHours}} hours and can only be used once.', 1),
('trans_email_verify_it', 'email_verification', 'it', 'Conferma la tua email DoorDrop', 'Attiva il tuo account con un clic. Il link è valido per 4 ore.', '<!doctype html><html lang="it"><body style="margin:0;background:#f8fafc;font-family:Arial,sans-serif;color:#0f172a;padding:28px 14px"><div style="max-width:560px;margin:auto;background:#fff;border:1px solid #e2e8f0;border-radius:18px;padding:32px"><div style="font-size:24px;font-weight:800;margin-bottom:24px">Door<span style="color:#2563eb">Drop</span></div><h1 style="font-size:24px;margin:0 0 14px">Conferma la tua email</h1><p style="font-size:14px;line-height:1.6;color:#475569">Ciao <strong>{{userName}}</strong>. Conferma <strong>{{userEmail}}</strong> per proteggere il tuo account e accedere a DoorDrop.</p><p style="text-align:center;margin:28px 0"><a href="{{verificationUrl}}" style="display:inline-block;background:#2563eb;color:#fff;padding:14px 24px;border-radius:10px;text-decoration:none;font-weight:700">Verifica la mia email</a></p><p style="font-size:13px;line-height:1.6;color:#64748b">Questo link è valido per <strong>{{expirationHours}} ore</strong> e può essere usato una sola volta. Se non hai creato questo account, puoi ignorare il messaggio.</p><p style="font-size:12px;color:#94a3b8;margin-top:28px">DoorDrop · Link di sicurezza dell’account</p></div></body></html>', 'Ciao {{userName}}, conferma la tua email {{userEmail}} qui: {{verificationUrl}}. Il link è valido per {{expirationHours}} ore e può essere usato una sola volta.', 1),
('trans_email_verify_fr', 'email_verification', 'fr', 'Confirmez votre e-mail DoorDrop', 'Activez votre compte en un clic. Le lien est valable 4 heures.', '<!doctype html><html lang="fr"><body style="margin:0;background:#f8fafc;font-family:Arial,sans-serif;color:#0f172a;padding:28px 14px"><div style="max-width:560px;margin:auto;background:#fff;border:1px solid #e2e8f0;border-radius:18px;padding:32px"><div style="font-size:24px;font-weight:800;margin-bottom:24px">Door<span style="color:#2563eb">Drop</span></div><h1 style="font-size:24px;margin:0 0 14px">Confirmez votre e-mail</h1><p style="font-size:14px;line-height:1.6;color:#475569">Bonjour <strong>{{userName}}</strong>. Confirmez <strong>{{userEmail}}</strong> pour protéger votre compte et accéder à DoorDrop.</p><p style="text-align:center;margin:28px 0"><a href="{{verificationUrl}}" style="display:inline-block;background:#2563eb;color:#fff;padding:14px 24px;border-radius:10px;text-decoration:none;font-weight:700">Vérifier mon e-mail</a></p><p style="font-size:13px;line-height:1.6;color:#64748b">Ce lien est valable pendant <strong>{{expirationHours}} heures</strong> et ne peut être utilisé qu’une seule fois. Si vous n’avez pas créé ce compte, ignorez ce message.</p><p style="font-size:12px;color:#94a3b8;margin-top:28px">DoorDrop · Lien de sécurité du compte</p></div></body></html>', 'Bonjour {{userName}}, confirmez votre e-mail {{userEmail}} ici : {{verificationUrl}}. Le lien est valable {{expirationHours}} heures et ne peut être utilisé qu’une seule fois.', 1),
('trans_email_verify_de', 'email_verification', 'de', 'Bestätigen Sie Ihre DoorDrop-E-Mail', 'Aktivieren Sie Ihr Konto mit einem Klick. Der Link ist 4 Stunden gültig.', '<!doctype html><html lang="de"><body style="margin:0;background:#f8fafc;font-family:Arial,sans-serif;color:#0f172a;padding:28px 14px"><div style="max-width:560px;margin:auto;background:#fff;border:1px solid #e2e8f0;border-radius:18px;padding:32px"><div style="font-size:24px;font-weight:800;margin-bottom:24px">Door<span style="color:#2563eb">Drop</span></div><h1 style="font-size:24px;margin:0 0 14px">E-Mail bestätigen</h1><p style="font-size:14px;line-height:1.6;color:#475569">Hallo <strong>{{userName}}</strong>. Bestätigen Sie <strong>{{userEmail}}</strong>, um Ihr Konto zu schützen und auf DoorDrop zuzugreifen.</p><p style="text-align:center;margin:28px 0"><a href="{{verificationUrl}}" style="display:inline-block;background:#2563eb;color:#fff;padding:14px 24px;border-radius:10px;text-decoration:none;font-weight:700">E-Mail bestätigen</a></p><p style="font-size:13px;line-height:1.6;color:#64748b">Dieser Link ist <strong>{{expirationHours}} Stunden</strong> gültig und kann nur einmal verwendet werden. Wenn Sie dieses Konto nicht erstellt haben, können Sie diese Nachricht ignorieren.</p><p style="font-size:12px;color:#94a3b8;margin-top:28px">DoorDrop · Sicherheitslink für Ihr Konto</p></div></body></html>', 'Hallo {{userName}}, bestätigen Sie Ihre E-Mail {{userEmail}} hier: {{verificationUrl}}. Der Link ist {{expirationHours}} Stunden gültig und kann nur einmal verwendet werden.', 1)
ON DUPLICATE KEY UPDATE
  subject = VALUES(subject), preheader = VALUES(preheader), body_html = VALUES(body_html), body_text = VALUES(body_text), is_active = VALUES(is_active);

INSERT INTO email_notification_events (event_code, template_id, category, label, description, audience, is_enabled) VALUES
('email_verification', 'email_verification', 'auth', 'Verificación de correo', 'Enlace de confirmación para registros con email y contraseña.', 'customer', 1)
ON DUPLICATE KEY UPDATE
  template_id = VALUES(template_id), category = VALUES(category), label = VALUES(label), description = VALUES(description), audience = VALUES(audience), is_enabled = VALUES(is_enabled);
